---
language: python

env:
  global:
    - HELM_URL=https://storage.googleapis.com/kubernetes-helm
    - HELM_TGZ=helm-v2.12.1-linux-amd64.tar.gz
    - TARGET_BR=gh-pages
    - REPO_DIR=/home/travis/build/moveaxlab/helm-charts
    - GH_URL=https://moveaxlab.github.io/helm-charts
    - REPO_URL=https://${GH_TOKEN}@github.com/moveaxlab/helm-charts.git
    - YAMLLINT_VERSION=1.8.1

install:
  # Installing Helm
  - wget -q ${HELM_URL}/${HELM_TGZ}
  - tar xzfv ${HELM_TGZ}
  - PATH=`pwd`/linux-amd64/:$PATH
  - helm init --client-only
  # Installig pip deps
  - sudo pip install yamllint=="${YAMLLINT_VERSION}"

before_script:

script:
  # Check charts format
  - >
    helm init --client-only;
    travis_terminate 1
  # Check YAML styling
  #- yamllint -c .yamllint.yml -s .travis.yml .yamllint.yml
  #- yamllint -c .yamllint.yml -s $(find . -type f -name "Chart.yaml")
  #- yamllint -c .yamllint.yml -s $(find . -type f -name "values.yaml")

after_success:
  - >
    if [ $TRAVIS_BRANCH = 'master' ] && [ $TRAVIS_PULL_REQUEST = 'false' ]; then
      # Temporary dir for storing new packaged charts and index files
      BUILD_DIR=$(mktemp -d)

      # Push temporary directory to the stack
      pushd $BUILD_DIR

      # Iterate over all charts are package them
      for dir in `ls ${REPO_DIR}/charts`; do
       helm dep update ${REPO_DIR}/charts/$dir
       helm package ${REPO_DIR}/charts/$dir
      done

      # Indexing of charts
      if [ -f index.yaml ]; then
       helm repo index --url ${GH_URL} --merge index.yaml .
      else
       helm repo index --url ${GH_URL} .
      fi

      # Pop temporary directory from the stack
      popd

      # List all the contents that we will push
      ls ${BUILD_DIR}

      # Clone repository and empty target branch
      git clone ${REPO_URL} out
      cd out
      git checkout ${TARGET_BR} || git checkout --orphan ${TARGET_BR}
      cd ..
      rm -rf out/* || exit 0

      # Copying contents of BUILD_DIR to out folder
      cp $BUILD_DIR/* out/
      cd out

      # Deploy if there are some changes
      git diff --quiet
      if [ $? != 0 ]; then
       # Add all new files to staging phase and commit the changes
       SHA=`git rev-parse --verify HEAD`
       git config user.name "Travis CI"
       git config user.email "travis@travis-ci.org"
       git add -A .
       git status
       git commit -m "Travis deploy ${SHA}"
       # We can push.
       git push ${REPO_URL}
      fi
    fi
