apiVersion: v1
name: proxy-injector
description: ProxyInjector chart that runs on kubernetes
appVersion: "v0.0.23"
version: 0.4.1
keywords:
  - Proxy
  - Authentication
  - kubernetes
home: https://github.com/stakater/ProxyInjector
maintainers:
- name: Stakater
  email: hello@stakater.com

